// AUTO-GENERATED by scripts/build-blog-manifest.mjs — do not edit by hand.
// Re-run `npm run prebuild` (or `npm run build`) to refresh.

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  ogImage: string;
  tags: string[];
  file: string;
}

export const POSTS: BlogPost[] = [
  {
    "slug": "why-verbum-exists",
    "title": "Why Verbum exists",
    "description": "A free Bible study app, built without a paywall, on top of public-domain data — and the AI that helped build it.",
    "date": "2026-04-25T00:00:00.000Z",
    "ogImage": "/og/why-verbum-exists.png",
    "tags": [
      "manifesto",
      "open-source",
      "mission"
    ],
    "file": "why-verbum-exists"
  },
  {
    "slug": "sentiment-labels-pt-es",
    "title": "How we manually labelled 62,209 verses for sentiment in Portuguese and Spanish",
    "description": "The methodology behind Verbum's emotional landscape — the trade-offs, the rubric, and why TextBlob alone wasn't enough.",
    "date": "2026-04-23T00:00:00.000Z",
    "ogImage": "/og/sentiment-labels-pt-es.png",
    "tags": [
      "methodology",
      "nlp",
      "sentiment-analysis",
      "multilingual"
    ],
    "file": "sentiment-labels-pt-es"
  },
  {
    "slug": "interlinear-strongs-explained",
    "title": "A practical guide to reading interlinear Hebrew and Greek",
    "description": "How Strong's numbers work, how to use the interlinear reader, and the kind of insight you can pull from it without learning the original languages.",
    "date": "2026-04-22T00:00:00.000Z",
    "ogImage": "/og/interlinear-strongs-explained.png",
    "tags": [
      "tutorial",
      "hebrew",
      "greek",
      "interlinear"
    ],
    "file": "interlinear-strongs-explained"
  },
  {
    "slug": "built-with-claude",
    "title": "Building Verbum with Claude as pair programmer",
    "description": "An honest postmortem of an AI-assisted full-stack project — what the model did well, where it failed, and how the working relationship was structured.",
    "date": "2026-04-21T00:00:00.000Z",
    "ogImage": "/og/built-with-claude.png",
    "tags": [
      "claude-ai",
      "anthropic",
      "postmortem",
      "software"
    ],
    "file": "built-with-claude"
  },
  {
    "slug": "twelve-translations",
    "title": "Twelve translations, five languages, one comparison view",
    "description": "How Verbum chose its 12 default Bible translations across English, Portuguese, Spanish, French, and German — and what each one is for.",
    "date": "2026-04-20T00:00:00.000Z",
    "ogImage": "/og/twelve-translations.png",
    "tags": [
      "translations",
      "multilingual",
      "methodology"
    ],
    "file": "twelve-translations"
  }
];
