"""Show sentiment labeling coverage per book and generate coverage.json + sentimentCoverage.ts.

Usage:
    python scripts/sentiment_status.py
    python scripts/sentiment_status.py --lang pt
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import duckdb

DB_PATH = "data/analytics/bible.duckdb"
COVERAGE_JSON = Path("data/processed/sentiment_pt/coverage.json")
COVERAGE_TS = Path("frontend/src/i18n/sentimentCoverage.ts")


def main() -> None:
    parser = argparse.ArgumentParser(description="Sentiment labeling coverage report")
    parser.add_argument("--lang", default="pt", help="Language to check (default: pt)")
    args = parser.parse_args()

    conn = duckdb.connect(DB_PATH, read_only=True)
    lang = args.lang

    total_df = conn.execute("""
        SELECT book_id, COUNT(*) AS total
        FROM verses
        WHERE translation_id = 'nvi'
        GROUP BY book_id
    """).fetchdf()

    labeled_df = conn.execute(
        """
        SELECT SPLIT_PART(verse_id, '.', 1) AS book_id, COUNT(*) AS labeled
        FROM verses_sentiment_multilang
        WHERE lang = ?
        GROUP BY book_id
        """,
        [lang],
    ).fetchdf()

    conn.close()

    totals = dict(zip(total_df["book_id"], total_df["total"]))
    labeled = dict(zip(labeled_df["book_id"], labeled_df["labeled"])) if not labeled_df.empty else {}

    coverage: dict[str, dict] = {}
    grand_total = 0
    grand_labeled = 0

    print(f"\n{'Book':<8} {'Labeled':>8} {'Total':>8} {'Coverage':>10}")
    print("-" * 40)

    for book_id in sorted(totals.keys()):
        t = totals[book_id]
        l = labeled.get(book_id, 0)
        pct = l / t if t > 0 else 0
        grand_total += t
        grand_labeled += l
        coverage[book_id] = {"total": int(t), "labeled": int(l), "pct": round(pct, 4)}
        bar = "█" * int(pct * 20) + "░" * (20 - int(pct * 20))
        status = "✅" if pct >= 1.0 else "⏳" if pct > 0 else "  "
        print(f"{book_id:<8} {l:>8} {t:>8} {pct:>9.1%}  {bar} {status}")

    grand_pct = grand_labeled / grand_total if grand_total > 0 else 0
    print("-" * 40)
    print(f"{'TOTAL':<8} {grand_labeled:>8} {grand_total:>8} {grand_pct:>9.1%}")

    summary = {
        "lang": lang,
        "total_verses": grand_total,
        "labeled_verses": grand_labeled,
        "coverage_pct": round(grand_pct, 4),
        "books": coverage,
    }

    COVERAGE_JSON.parent.mkdir(parents=True, exist_ok=True)
    COVERAGE_JSON.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"\nSaved: {COVERAGE_JSON}")

    books_done = {bid for bid, info in coverage.items() if info["pct"] >= 1.0}
    ts_content = (
        "// Auto-generated by scripts/sentiment_status.py — do not edit manually\n"
        "export const SENTIMENT_COVERED_PT: ReadonlySet<string> = new Set([\n"
    )
    for bid in sorted(books_done):
        ts_content += f'  "{bid}",\n'
    ts_content += "]);\n"

    COVERAGE_TS.write_text(ts_content, encoding="utf-8")
    print(f"Saved: {COVERAGE_TS}")


if __name__ == "__main__":
    main()
