"""Show sentiment labeling coverage per book and generate coverage.json + sentimentCoverage.ts.

Usage:
    python scripts/sentiment_status.py                 # all langs (pt + es)
    python scripts/sentiment_status.py --lang pt       # only PT
    python scripts/sentiment_status.py --lang es       # only ES

Always regenerates the TS file with both SENTIMENT_COVERED_PT and
SENTIMENT_COVERED_ES constants (empty sets if never labeled).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import duckdb

DB_PATH = "data/analytics/bible.duckdb"
COVERAGE_TS = Path("frontend/src/i18n/sentimentCoverage.ts")

LANG_TRANSLATION = {"pt": "nvi", "es": "rvr"}


def compute_coverage(conn: duckdb.DuckDBPyConnection, lang: str) -> dict:
    target_translation = LANG_TRANSLATION[lang]
    total_df = conn.execute(
        "SELECT book_id, COUNT(*) AS total FROM verses WHERE translation_id = ? GROUP BY book_id",
        [target_translation],
    ).fetchdf()
    labeled_df = conn.execute(
        """
        SELECT SPLIT_PART(verse_id, '.', 1) AS book_id, COUNT(*) AS labeled
        FROM verses_sentiment_multilang
        WHERE lang = ?
        GROUP BY book_id
        """,
        [lang],
    ).fetchdf()

    totals = dict(zip(total_df["book_id"], total_df["total"]))
    labeled = dict(zip(labeled_df["book_id"], labeled_df["labeled"])) if not labeled_df.empty else {}

    coverage: dict[str, dict] = {}
    grand_total = grand_labeled = 0
    for book_id in sorted(totals.keys()):
        t = totals[book_id]
        l = labeled.get(book_id, 0)
        pct = l / t if t > 0 else 0
        grand_total += t
        grand_labeled += l
        coverage[book_id] = {"total": int(t), "labeled": int(l), "pct": round(pct, 4)}

    return {
        "lang": lang,
        "total_verses": grand_total,
        "labeled_verses": grand_labeled,
        "coverage_pct": round(grand_labeled / grand_total if grand_total else 0, 4),
        "books": coverage,
    }


def print_report(summary: dict) -> None:
    print(f"\n=== {summary['lang'].upper()} coverage ===")
    print(f"{'Book':<8} {'Labeled':>8} {'Total':>8} {'Coverage':>10}")
    print("-" * 40)
    for book_id, info in summary["books"].items():
        pct = info["pct"]
        bar = "█" * int(pct * 20) + "░" * (20 - int(pct * 20))
        status = "✅" if pct >= 1.0 else "⏳" if pct > 0 else "  "
        print(f"{book_id:<8} {info['labeled']:>8} {info['total']:>8} {pct:>9.1%}  {bar} {status}")
    print("-" * 40)
    print(f"{'TOTAL':<8} {summary['labeled_verses']:>8} {summary['total_verses']:>8} {summary['coverage_pct']:>9.1%}")


def render_ts(covered_pt: set[str], covered_es: set[str]) -> str:
    def render_set(name: str, covered: set[str]) -> str:
        out = f"export const {name}: ReadonlySet<string> = new Set([\n"
        for bid in sorted(covered):
            out += f'  "{bid}",\n'
        out += "]);\n"
        return out

    header = "// Auto-generated by scripts/sentiment_status.py — do not edit manually\n\n"
    return header + render_set("SENTIMENT_COVERED_PT", covered_pt) + "\n" + render_set("SENTIMENT_COVERED_ES", covered_es)


def main() -> None:
    parser = argparse.ArgumentParser(description="Sentiment labeling coverage report")
    parser.add_argument("--lang", choices=["pt", "es"], help="Only compute one language (omit for both)")
    args = parser.parse_args()

    conn = duckdb.connect(DB_PATH, read_only=True)
    langs = [args.lang] if args.lang else ["pt", "es"]

    summaries: dict[str, dict] = {}
    for lang in langs:
        summaries[lang] = compute_coverage(conn, lang)
    conn.close()

    # Always recompute both langs for the TS file so neither is dropped.
    conn2 = duckdb.connect(DB_PATH, read_only=True)
    all_summaries = {"pt": compute_coverage(conn2, "pt"), "es": compute_coverage(conn2, "es")}
    conn2.close()

    for lang, summary in summaries.items():
        print_report(summary)
        out_json = Path(f"data/processed/sentiment_{lang}/coverage.json")
        out_json.parent.mkdir(parents=True, exist_ok=True)
        out_json.write_text(json.dumps(summary, indent=2), encoding="utf-8")
        print(f"\nSaved: {out_json}")

    covered_pt = {bid for bid, info in all_summaries["pt"]["books"].items() if info["pct"] >= 1.0}
    covered_es = {bid for bid, info in all_summaries["es"]["books"].items() if info["pct"] >= 1.0}

    COVERAGE_TS.write_text(render_ts(covered_pt, covered_es), encoding="utf-8")
    print(f"Saved: {COVERAGE_TS}")
    print(f"  PT covered books: {len(covered_pt)} · ES covered books: {len(covered_es)}")


if __name__ == "__main__":
    main()
