"""One-shot script: populate dictionary_entries_multilang.name for PT/ES."""
import duckdb
import re

db = duckdb.connect("data/analytics/bible.duckdb")

# Get unmatched entries (name IS NULL)
unmatched = db.execute("""
    SELECT DISTINCT e.slug, e.name
    FROM dictionary_entries e
    JOIN dictionary_entries_multilang m ON m.slug = e.slug
    WHERE m.lang = 'pt' AND m.name IS NULL
    ORDER BY e.slug
""").fetchall()

print(f"Unmatched: {len(unmatched)}")

# ── Well-known biblical name mappings ──
KNOWN_PT = {
    "Aaron": "Arão", "Abel": "Abel", "Abraham": "Abraão", "Absalom": "Absalão",
    "Adam": "Adão", "Ahab": "Acabe", "Amos": "Amós", "Andrew": "André",
    "Babylon": "Babilônia", "Barnabas": "Barnabé", "Bartholomew": "Bartolomeu",
    "Bathsheba": "Bate-Seba", "Benjamin": "Benjamim", "Bethany": "Betânia",
    "Bethlehem": "Belém", "Boaz": "Boaz", "Cain": "Caim", "Canaan": "Canaã",
    "Christ": "Cristo", "Cornelius": "Cornélio", "Damascus": "Damasco",
    "Daniel": "Daniel", "David": "Davi", "Deborah": "Débora",
    "Deuteronomy": "Deuteronômio",
    "Egypt": "Egito", "Eli": "Eli", "Elijah": "Elias", "Elisha": "Eliseu",
    "Enoch": "Enoque", "Ephraim": "Efraim", "Esau": "Esaú", "Esther": "Ester",
    "Eve": "Eva", "Exodus": "Êxodo", "Ezekiel": "Ezequiel", "Ezra": "Esdras",
    "Gabriel": "Gabriel", "Galilee": "Galileia", "Genesis": "Gênesis",
    "Gideon": "Gideão", "Goliath": "Golias", "Habakkuk": "Habacuque",
    "Hagar": "Agar", "Haggai": "Ageu", "Hannah": "Ana", "Herod": "Herodes",
    "Hezekiah": "Ezequias", "Hosea": "Oseias", "Isaac": "Isaque",
    "Isaiah": "Isaías", "Ishmael": "Ismael", "Israel": "Israel",
    "Jacob": "Jacó", "James": "Tiago", "Jeremiah": "Jeremias",
    "Jericho": "Jericó", "Jerusalem": "Jerusalém", "Jesse": "Jessé",
    "Jesus": "Jesus", "Jezebel": "Jezabel", "Joab": "Joabe", "Job": "Jó",
    "Joel": "Joel", "John": "João", "Jonah": "Jonas", "Jonathan": "Jônatas",
    "Jordan": "Jordão", "Joseph": "José", "Joshua": "Josué", "Josiah": "Josias",
    "Judah": "Judá", "Judas": "Judas", "Judges": "Juízes",
    "Kings": "Reis", "Laban": "Labão", "Lamentations": "Lamentações",
    "Lazarus": "Lázaro", "Leah": "Leia", "Lebanon": "Líbano",
    "Levi": "Levi", "Leviticus": "Levítico", "Luke": "Lucas",
    "Malachi": "Malaquias", "Mark": "Marcos", "Martha": "Marta",
    "Mary": "Maria", "Matthew": "Mateus", "Melchizedek": "Melquisedeque",
    "Micah": "Miqueias", "Michael": "Miguel", "Miriam": "Miriã",
    "Moses": "Moisés", "Naaman": "Naamã", "Nahum": "Naum",
    "Nathan": "Natã", "Nazareth": "Nazaré", "Nebuchadnezzar": "Nabucodonosor",
    "Nehemiah": "Neemias", "Nineveh": "Nínive", "Noah": "Noé",
    "Numbers": "Números", "Obadiah": "Obadias", "Paul": "Paulo",
    "Peter": "Pedro", "Pharaoh": "Faraó", "Philip": "Filipe",
    "Philistines": "Filisteus", "Pilate": "Pilatos", "Proverbs": "Provérbios",
    "Psalms": "Salmos", "Rachel": "Raquel", "Rahab": "Raabe",
    "Rebekah": "Rebeca", "Reuben": "Rúben", "Revelation": "Apocalipse",
    "Romans": "Romanos", "Ruth": "Rute", "Samaria": "Samaria",
    "Samson": "Sansão", "Samuel": "Samuel", "Sarah": "Sara",
    "Satan": "Satanás", "Saul": "Saul", "Silas": "Silas",
    "Simeon": "Simeão", "Simon": "Simão", "Sinai": "Sinai",
    "Solomon": "Salomão", "Stephen": "Estêvão", "Timothy": "Timóteo",
    "Titus": "Tito", "Zechariah": "Zacarias", "Zephaniah": "Sofonias",
    "Zion": "Sião",
    "Atonement": "Expiação", "Baptism": "Batismo", "Bible": "Bíblia",
    "Blessing": "Bênção", "Blood": "Sangue", "Book": "Livro",
    "Bread": "Pão", "Burial": "Sepultamento", "Captivity": "Cativeiro",
    "Church": "Igreja", "Circumcision": "Circuncisão",
    "Commandments": "Mandamentos",
    "Communion": "Comunhão", "Conscience": "Consciência", "Covenant": "Aliança",
    "Creation": "Criação", "Cross": "Cruz", "Crown": "Coroa",
    "Darkness": "Trevas", "Death": "Morte", "Devil": "Diabo",
    "Disciple": "Discípulo", "Dream": "Sonho", "Eagle": "Águia",
    "Earthquake": "Terremoto", "Elder": "Ancião", "Epistle": "Epístola",
    "Faith": "Fé", "Famine": "Fome", "Feast": "Festa",
    "Fire": "Fogo", "Flood": "Dilúvio", "Forgiveness": "Perdão",
    "Furnace": "Fornalha", "Garden": "Jardim", "Gate": "Porta",
    "Ghost": "Espírito", "Glory": "Glória", "God": "Deus",
    "Gold": "Ouro", "Gospel": "Evangelho", "Grace": "Graça",
    "Grave": "Sepulcro", "Harp": "Harpa", "Harvest": "Colheita",
    "Healing": "Cura", "Heart": "Coração", "Heaven": "Céu",
    "Hell": "Inferno", "High-priest": "Sumo Sacerdote", "Holiness": "Santidade",
    "Hope": "Esperança", "Idol": "Ídolo", "Idolatry": "Idolatria",
    "Image": "Imagem", "Incense": "Incenso", "Inheritance": "Herança",
    "Iniquity": "Iniquidade", "Inspiration": "Inspiração", "Iron": "Ferro",
    "Jealousy": "Ciúme", "Joy": "Alegria", "Judgment": "Julgamento",
    "Justice": "Justiça", "King": "Rei", "Kingdom": "Reino",
    "Knowledge": "Conhecimento", "Lamb": "Cordeiro", "Lamp": "Lâmpada",
    "Law": "Lei", "Leprosy": "Lepra", "Life": "Vida",
    "Light": "Luz", "Lion": "Leão", "Lord": "Senhor",
    "Love": "Amor", "Manna": "Maná", "Marriage": "Casamento",
    "Mercy": "Misericórdia", "Messenger": "Mensageiro", "Miracle": "Milagre",
    "Miracles": "Milagres", "Mountain": "Montanha", "Murder": "Assassinato",
    "Mystery": "Mistério", "Night": "Noite", "Oath": "Juramento",
    "Offering": "Oferta", "Olive": "Oliveira", "Oracle": "Oráculo",
    "Parable": "Parábola", "Paradise": "Paraíso", "Passover": "Páscoa",
    "Peace": "Paz", "Pentecost": "Pentecostes", "Persecution": "Perseguição",
    "Plague": "Praga", "Prayer": "Oração", "Priest": "Sacerdote",
    "Prison": "Prisão", "Promise": "Promessa", "Prophecy": "Profecia",
    "Prophet": "Profeta", "Psalm": "Salmo", "Punishment": "Punição",
    "Purification": "Purificação", "Rain": "Chuva", "Redemption": "Redenção",
    "Repentance": "Arrependimento", "Resurrection": "Ressurreição",
    "Righteousness": "Justiça", "Sabbath": "Sábado", "Sacrifice": "Sacrifício",
    "Salvation": "Salvação", "Sanctification": "Santificação",
    "Sanctuary": "Santuário", "Seed": "Semente", "Serpent": "Serpente",
    "Shepherd": "Pastor", "Shield": "Escudo", "Sin": "Pecado",
    "Slavery": "Escravidão", "Soul": "Alma", "Spirit": "Espírito",
    "Star": "Estrela", "Stone": "Pedra", "Sword": "Espada",
    "Synagogue": "Sinagoga", "Tabernacle": "Tabernáculo", "Temple": "Templo",
    "Temptation": "Tentação", "Throne": "Trono", "Tithe": "Dízimo",
    "Tomb": "Tumba", "Tongue": "Língua", "Tower": "Torre",
    "Tree": "Árvore", "Tribe": "Tribo", "Truth": "Verdade",
    "Vineyard": "Vinha", "Virgin": "Virgem", "Vision": "Visão",
    "Voice": "Voz", "War": "Guerra", "Water": "Água",
    "Widow": "Viúva", "Wilderness": "Deserto", "Wine": "Vinho",
    "Wisdom": "Sabedoria", "Witness": "Testemunha", "Word": "Palavra",
    "Worship": "Adoração", "Wrath": "Ira", "Zeal": "Zelo",
    "Antioch": "Antioquia", "Ararat": "Ararate", "Assyria": "Assíria",
    "Athens": "Atenas", "Corinth": "Corinto", "Crete": "Creta",
    "Cyprus": "Chipre", "Edom": "Edom", "Ephesus": "Éfeso",
    "Ethiopia": "Etiópia", "Galatia": "Galácia", "Gilead": "Gileade",
    "Greece": "Grécia", "Hebron": "Hebrom", "Hermon": "Hermom",
    "Macedonia": "Macedônia", "Mesopotamia": "Mesopotâmia", "Moab": "Moabe",
    "Olivet": "Oliveiras", "Persia": "Pérsia", "Philippi": "Filipos",
    "Phoenicia": "Fenícia", "Rome": "Roma", "Sardis": "Sardes",
    "Sheba": "Sabá", "Sidon": "Sidom", "Sodom": "Sodoma",
    "Syria": "Síria", "Tarsus": "Tarso", "Thessalonica": "Tessalônica",
    "Troy": "Trôade", "Tyre": "Tiro",
    # Additional common terms
    "Altar": "Altar", "Angel": "Anjo", "Angels": "Anjos",
    "Apostle": "Apóstolo", "Ark": "Arca", "Army": "Exército",
    "Ascension": "Ascensão", "Bath": "Banho", "Battle": "Batalha",
    "Bear": "Urso", "Bed": "Cama", "Bell": "Sino", "Belt": "Cinto",
    "Bondage": "Escravidão", "Bow": "Arco", "Boy": "Menino",
    "Branch": "Ramo", "Brass": "Bronze", "Brother": "Irmão",
    "Bull": "Touro", "Bullock": "Novilho", "Calf": "Bezerro",
    "Camel": "Camelo", "Camp": "Acampamento", "Captain": "Capitão",
    "Cedar": "Cedro", "Chain": "Corrente", "Chamber": "Câmara",
    "Chariot": "Carro", "Cities": "Cidades", "Cloud": "Nuvem",
    "Cock": "Galo", "Colour": "Cor", "Copper": "Cobre",
    "Corn": "Grão", "Cotton": "Algodão", "Cup": "Cálice",
    "Curse": "Maldição", "Dance": "Dança", "Daughter": "Filha",
    "Day": "Dia", "Desert": "Deserto", "Dog": "Cão",
    "Door": "Porta", "Dove": "Pomba", "Dress": "Veste",
    "Drink": "Bebida", "Dust": "Pó", "Dwelling": "Habitação",
    "Ear": "Orelha", "Earth": "Terra", "East": "Oriente",
    "Enemy": "Inimigo", "Evening": "Tarde", "Eye": "Olho",
    "Face": "Rosto", "Father": "Pai", "Fear": "Temor",
    "Fig": "Figo", "Fish": "Peixe", "Flesh": "Carne",
    "Flock": "Rebanho", "Fool": "Tolo", "Foot": "Pé",
    "Forest": "Floresta", "Fountain": "Fonte", "Fox": "Raposa",
    "Fruit": "Fruto", "Giant": "Gigante", "Gift": "Presente",
    "Glass": "Vidro", "Goat": "Bode", "Grape": "Uva",
    "Grass": "Erva", "Hair": "Cabelo", "Hand": "Mão",
    "Head": "Cabeça", "Herb": "Erva", "Hill": "Colina",
    "Honey": "Mel", "Horn": "Chifre", "Horse": "Cavalo",
    "Hour": "Hora", "House": "Casa", "Hunger": "Fome",
    "Inn": "Estalagem", "Island": "Ilha", "Ivory": "Marfim",
    "Jewel": "Joia", "Key": "Chave", "Knife": "Faca",
    "Lace": "Laço", "Lead": "Chumbo", "Leaf": "Folha",
    "Leopard": "Leopardo", "Letter": "Carta", "Linen": "Linho",
    "Lizard": "Lagarto", "Locust": "Gafanhoto", "Lute": "Alaúde",
    "Manger": "Manjedoura", "Market": "Mercado", "Meat": "Carne",
    "Milk": "Leite", "Mill": "Moinho", "Mirror": "Espelho",
    "Money": "Dinheiro", "Moon": "Lua", "Morning": "Manhã",
    "Moth": "Traça", "Mother": "Mãe", "Mouth": "Boca",
    "Mule": "Mula", "Nail": "Prego", "Needle": "Agulha",
    "Nest": "Ninho", "Net": "Rede", "North": "Norte",
    "Nose": "Nariz", "Nut": "Noz", "Oak": "Carvalho",
    "Oil": "Óleo", "Onion": "Cebola", "Oven": "Forno",
    "Owl": "Coruja", "Ox": "Boi", "Palace": "Palácio",
    "Palm": "Palmeira", "Pearl": "Pérola", "Pen": "Pena",
    "Pit": "Cova", "Plain": "Planície", "Plow": "Arado",
    "Pool": "Tanque", "Pot": "Panela", "Pottery": "Cerâmica",
    "Prince": "Príncipe", "Queen": "Rainha", "Quiver": "Aljava",
    "Reed": "Junco", "Ring": "Anel", "River": "Rio",
    "Road": "Estrada", "Robe": "Manto", "Rock": "Rocha",
    "Rod": "Vara", "Roof": "Telhado", "Root": "Raiz",
    "Rope": "Corda", "Rose": "Rosa", "Ruby": "Rubi",
    "Rust": "Ferrugem", "Salt": "Sal", "Sand": "Areia",
    "Seal": "Selo", "Servant": "Servo", "Shadow": "Sombra",
    "Sheep": "Ovelha", "Ship": "Navio", "Shoe": "Sandália",
    "Shoulder": "Ombro", "Sickle": "Foice", "Silver": "Prata",
    "Skin": "Pele", "Slave": "Escravo", "Smoke": "Fumaça",
    "Snow": "Neve", "Soldier": "Soldado", "Song": "Cântico",
    "South": "Sul", "Spear": "Lança", "Spice": "Especiaria",
    "Spring": "Fonte", "Staff": "Cajado", "Sun": "Sol",
    "Table": "Mesa", "Talent": "Talento", "Tares": "Joio",
    "Tent": "Tenda", "Thief": "Ladrão", "Thorn": "Espinho",
    "Thunder": "Trovão", "Tin": "Estanho", "Trumpet": "Trombeta",
    "Turtle": "Rola", "Valley": "Vale", "Veil": "Véu",
    "Vine": "Videira", "Viper": "Víbora", "Vow": "Voto",
    "Wall": "Muro", "Wasp": "Vespa", "Wave": "Onda",
    "Wax": "Cera", "Weapon": "Arma", "Well": "Poço",
    "Whale": "Baleia", "Wheat": "Trigo", "Wheel": "Roda",
    "Whip": "Chicote", "Wicked": "Ímpio", "Wolf": "Lobo",
    "Wood": "Madeira", "Wool": "Lã", "Worm": "Verme",
    "Yoke": "Jugo",
    # Additional theological/religious terms
    "Abomination": "Abominação", "Ablution": "Ablução",
    "Adjuration": "Adjuração", "Adoption": "Adoção",
    "Adultery": "Adultério", "Advocate": "Advogado",
    "Affinity": "Afinidade", "Agriculture": "Agricultura",
    "Allegory": "Alegoria", "Alliance": "Aliança",
    "Alms": "Esmola", "Anointing": "Unção",
    "Antichrist": "Anticristo", "Apocrypha": "Apócrifos",
    "Apostasy": "Apostasia", "Architecture": "Arquitetura",
    "Archery": "Arco e Flecha",
    "Assurance": "Segurança", "Astronomy": "Astronomia",
    "Banishment": "Banimento", "Blasphemy": "Blasfêmia",
    "Blindness": "Cegueira", "Bondage": "Servidão",
    "Candlestick": "Candelabro", "Census": "Censo",
    "Concubine": "Concubina", "Confession": "Confissão",
    "Congregation": "Congregação", "Consecration": "Consagração",
    "Conversion": "Conversão", "Crucifixion": "Crucificação",
    "Divination": "Adivinhação", "Divorce": "Divórcio",
    "Doxology": "Doxologia", "Election": "Eleição",
    "Embalming": "Embalsamamento", "Enchantments": "Encantamentos",
    "Excommunication": "Excomunhão", "Exile": "Exílio",
    "Expiation": "Expiação", "Fasting": "Jejum",
    "Fellowship": "Comunhão", "Firstborn": "Primogênito",
    "Genealogy": "Genealogia", "Gentiles": "Gentios",
    "Glorification": "Glorificação", "Hospitality": "Hospitalidade",
    "Humility": "Humildade", "Hymn": "Hino",
    "Intercession": "Intercessão", "Interpretation": "Interpretação",
    "Justification": "Justificação", "Kinsman": "Parente",
    "Lamentation": "Lamentação", "Liberation": "Libertação",
    "Liturgy": "Liturgia", "Manifestation": "Manifestação",
    "Meditation": "Meditação", "Minstrel": "Menestrel",
    "Oblation": "Oblação", "Ordination": "Ordenação",
    "Patriarch": "Patriarca", "Perfection": "Perfeição",
    "Pilgrimage": "Peregrinação", "Proclamation": "Proclamação",
    "Propitiation": "Propiciação", "Providence": "Providência",
    "Reconciliation": "Reconciliação", "Regeneration": "Regeneração",
    "Remnant": "Remanescente", "Restoration": "Restauração",
    "Retribution": "Retribuição", "Revelation": "Revelação",
    "Sanctification": "Santificação", "Scribe": "Escriba",
    "Sorcery": "Feitiçaria", "Supplication": "Súplica",
    "Transfiguration": "Transfiguração", "Tribulation": "Tribulação",
    "Uncleanness": "Impureza", "Usury": "Usura",
    "Vengeance": "Vingança",
}

KNOWN_ES = {
    "Aaron": "Aarón", "Abel": "Abel", "Abraham": "Abraham", "Absalom": "Absalón",
    "Adam": "Adán", "Ahab": "Acab", "Amos": "Amós", "Andrew": "Andrés",
    "Babylon": "Babilonia", "Barnabas": "Bernabé", "Bartholomew": "Bartolomé",
    "Bathsheba": "Betsabé", "Benjamin": "Benjamín", "Bethany": "Betania",
    "Bethlehem": "Belén", "Boaz": "Booz", "Cain": "Caín", "Canaan": "Canaán",
    "Christ": "Cristo", "Cornelius": "Cornelio", "Damascus": "Damasco",
    "Daniel": "Daniel", "David": "David", "Deborah": "Débora",
    "Deuteronomy": "Deuteronomio",
    "Egypt": "Egipto", "Eli": "Elí", "Elijah": "Elías", "Elisha": "Eliseo",
    "Enoch": "Enoc", "Ephraim": "Efraín", "Esau": "Esaú", "Esther": "Ester",
    "Eve": "Eva", "Exodus": "Éxodo", "Ezekiel": "Ezequiel", "Ezra": "Esdras",
    "Gabriel": "Gabriel", "Galilee": "Galilea", "Genesis": "Génesis",
    "Gideon": "Gedeón", "Goliath": "Goliat", "Habakkuk": "Habacuc",
    "Hagar": "Agar", "Haggai": "Hageo", "Hannah": "Ana", "Herod": "Herodes",
    "Hezekiah": "Ezequías", "Hosea": "Oseas", "Isaac": "Isaac",
    "Isaiah": "Isaías", "Ishmael": "Ismael", "Israel": "Israel",
    "Jacob": "Jacob", "James": "Santiago", "Jeremiah": "Jeremías",
    "Jericho": "Jericó", "Jerusalem": "Jerusalén", "Jesse": "Isaí",
    "Jesus": "Jesús", "Jezebel": "Jezabel", "Joab": "Joab", "Job": "Job",
    "Joel": "Joel", "John": "Juan", "Jonah": "Jonás", "Jonathan": "Jonatán",
    "Jordan": "Jordán", "Joseph": "José", "Joshua": "Josué", "Josiah": "Josías",
    "Judah": "Judá", "Judas": "Judas", "Judges": "Jueces",
    "Kings": "Reyes", "Laban": "Labán", "Lamentations": "Lamentaciones",
    "Lazarus": "Lázaro", "Leah": "Lea", "Lebanon": "Líbano",
    "Levi": "Leví", "Leviticus": "Levítico", "Luke": "Lucas",
    "Malachi": "Malaquías", "Mark": "Marcos", "Martha": "Marta",
    "Mary": "María", "Matthew": "Mateo", "Melchizedek": "Melquisedec",
    "Micah": "Miqueas", "Michael": "Miguel", "Miriam": "Miriam",
    "Moses": "Moisés", "Naaman": "Naamán", "Nahum": "Nahúm",
    "Nathan": "Natán", "Nazareth": "Nazaret", "Nebuchadnezzar": "Nabucodonosor",
    "Nehemiah": "Nehemías", "Nineveh": "Nínive", "Noah": "Noé",
    "Numbers": "Números", "Obadiah": "Abdías", "Paul": "Pablo",
    "Peter": "Pedro", "Pharaoh": "Faraón", "Philip": "Felipe",
    "Philistines": "Filisteos", "Pilate": "Pilato", "Proverbs": "Proverbios",
    "Psalms": "Salmos", "Rachel": "Raquel", "Rahab": "Rahab",
    "Rebekah": "Rebeca", "Reuben": "Rubén", "Revelation": "Apocalipsis",
    "Romans": "Romanos", "Ruth": "Rut", "Samaria": "Samaria",
    "Samson": "Sansón", "Samuel": "Samuel", "Sarah": "Sara",
    "Satan": "Satanás", "Saul": "Saúl", "Silas": "Silas",
    "Simeon": "Simeón", "Simon": "Simón", "Sinai": "Sinaí",
    "Solomon": "Salomón", "Stephen": "Esteban", "Timothy": "Timoteo",
    "Titus": "Tito", "Zechariah": "Zacarías", "Zephaniah": "Sofonías",
    "Zion": "Sion",
    "Atonement": "Expiación", "Baptism": "Bautismo", "Bible": "Biblia",
    "Blessing": "Bendición", "Blood": "Sangre", "Book": "Libro",
    "Bread": "Pan", "Burial": "Sepultura", "Captivity": "Cautividad",
    "Church": "Iglesia", "Circumcision": "Circuncisión",
    "Commandments": "Mandamientos",
    "Communion": "Comunión", "Conscience": "Conciencia", "Covenant": "Pacto",
    "Creation": "Creación", "Cross": "Cruz", "Crown": "Corona",
    "Darkness": "Tinieblas", "Death": "Muerte", "Devil": "Diablo",
    "Disciple": "Discípulo", "Dream": "Sueño", "Eagle": "Águila",
    "Earthquake": "Terremoto", "Elder": "Anciano", "Epistle": "Epístola",
    "Faith": "Fe", "Famine": "Hambruna", "Feast": "Fiesta",
    "Fire": "Fuego", "Flood": "Diluvio", "Forgiveness": "Perdón",
    "Furnace": "Horno", "Garden": "Jardín", "Gate": "Puerta",
    "Ghost": "Espíritu", "Glory": "Gloria", "God": "Dios",
    "Gold": "Oro", "Gospel": "Evangelio", "Grace": "Gracia",
    "Grave": "Sepulcro", "Harp": "Arpa", "Harvest": "Cosecha",
    "Healing": "Sanación", "Heart": "Corazón", "Heaven": "Cielo",
    "Hell": "Infierno", "High-priest": "Sumo Sacerdote", "Holiness": "Santidad",
    "Hope": "Esperanza", "Idol": "Ídolo", "Idolatry": "Idolatría",
    "Image": "Imagen", "Incense": "Incienso", "Inheritance": "Herencia",
    "Iniquity": "Iniquidad", "Inspiration": "Inspiración", "Iron": "Hierro",
    "Jealousy": "Celos", "Joy": "Gozo", "Judgment": "Juicio",
    "Justice": "Justicia", "King": "Rey", "Kingdom": "Reino",
    "Knowledge": "Conocimiento", "Lamb": "Cordero", "Lamp": "Lámpara",
    "Law": "Ley", "Leprosy": "Lepra", "Life": "Vida",
    "Light": "Luz", "Lion": "León", "Lord": "Señor",
    "Love": "Amor", "Manna": "Maná", "Marriage": "Matrimonio",
    "Mercy": "Misericordia", "Messenger": "Mensajero", "Miracle": "Milagro",
    "Miracles": "Milagros", "Mountain": "Montaña", "Murder": "Asesinato",
    "Mystery": "Misterio", "Night": "Noche", "Oath": "Juramento",
    "Offering": "Ofrenda", "Olive": "Olivo", "Oracle": "Oráculo",
    "Parable": "Parábola", "Paradise": "Paraíso", "Passover": "Pascua",
    "Peace": "Paz", "Pentecost": "Pentecostés", "Persecution": "Persecución",
    "Plague": "Plaga", "Prayer": "Oración", "Priest": "Sacerdote",
    "Prison": "Prisión", "Promise": "Promesa", "Prophecy": "Profecía",
    "Prophet": "Profeta", "Psalm": "Salmo", "Punishment": "Castigo",
    "Purification": "Purificación", "Rain": "Lluvia", "Redemption": "Redención",
    "Repentance": "Arrepentimiento", "Resurrection": "Resurrección",
    "Righteousness": "Justicia", "Sabbath": "Sábado", "Sacrifice": "Sacrificio",
    "Salvation": "Salvación", "Sanctification": "Santificación",
    "Sanctuary": "Santuario", "Seed": "Semilla", "Serpent": "Serpiente",
    "Shepherd": "Pastor", "Shield": "Escudo", "Sin": "Pecado",
    "Slavery": "Esclavitud", "Soul": "Alma", "Spirit": "Espíritu",
    "Star": "Estrella", "Stone": "Piedra", "Sword": "Espada",
    "Synagogue": "Sinagoga", "Tabernacle": "Tabernáculo", "Temple": "Templo",
    "Temptation": "Tentación", "Throne": "Trono", "Tithe": "Diezmo",
    "Tomb": "Tumba", "Tongue": "Lengua", "Tower": "Torre",
    "Tree": "Árbol", "Tribe": "Tribu", "Truth": "Verdad",
    "Vineyard": "Viña", "Virgin": "Virgen", "Vision": "Visión",
    "Voice": "Voz", "War": "Guerra", "Water": "Agua",
    "Widow": "Viuda", "Wilderness": "Desierto", "Wine": "Vino",
    "Wisdom": "Sabiduría", "Witness": "Testigo", "Word": "Palabra",
    "Worship": "Adoración", "Wrath": "Ira", "Zeal": "Celo",
    "Antioch": "Antioquía", "Ararat": "Ararat", "Assyria": "Asiria",
    "Athens": "Atenas", "Corinth": "Corinto", "Crete": "Creta",
    "Cyprus": "Chipre", "Edom": "Edom", "Ephesus": "Éfeso",
    "Ethiopia": "Etiopía", "Galatia": "Galacia", "Gilead": "Galaad",
    "Greece": "Grecia", "Hebron": "Hebrón", "Hermon": "Hermón",
    "Macedonia": "Macedonia", "Mesopotamia": "Mesopotamia", "Moab": "Moab",
    "Olivet": "Olivos", "Persia": "Persia", "Philippi": "Filipos",
    "Phoenicia": "Fenicia", "Rome": "Roma", "Sardis": "Sardis",
    "Sheba": "Saba", "Sidon": "Sidón", "Sodom": "Sodoma",
    "Syria": "Siria", "Tarsus": "Tarso", "Thessalonica": "Tesalónica",
    "Troy": "Tróade", "Tyre": "Tiro",
    # Additional common terms
    "Altar": "Altar", "Angel": "Ángel", "Angels": "Ángeles",
    "Apostle": "Apóstol", "Ark": "Arca", "Army": "Ejército",
    "Ascension": "Ascensión", "Bath": "Baño", "Battle": "Batalla",
    "Bear": "Oso", "Bed": "Cama", "Bell": "Campana", "Belt": "Cinturón",
    "Bondage": "Servidumbre", "Bow": "Arco", "Boy": "Niño",
    "Branch": "Rama", "Brass": "Bronce", "Brother": "Hermano",
    "Bull": "Toro", "Bullock": "Novillo", "Calf": "Becerro",
    "Camel": "Camello", "Camp": "Campamento", "Captain": "Capitán",
    "Cedar": "Cedro", "Chain": "Cadena", "Chamber": "Cámara",
    "Chariot": "Carro", "Cities": "Ciudades", "Cloud": "Nube",
    "Cock": "Gallo", "Colour": "Color", "Copper": "Cobre",
    "Corn": "Grano", "Cotton": "Algodón", "Cup": "Cáliz",
    "Curse": "Maldición", "Dance": "Danza", "Daughter": "Hija",
    "Day": "Día", "Desert": "Desierto", "Dog": "Perro",
    "Door": "Puerta", "Dove": "Paloma", "Dress": "Vestido",
    "Drink": "Bebida", "Dust": "Polvo", "Dwelling": "Morada",
    "Ear": "Oreja", "Earth": "Tierra", "East": "Oriente",
    "Enemy": "Enemigo", "Evening": "Tarde", "Eye": "Ojo",
    "Face": "Rostro", "Father": "Padre", "Fear": "Temor",
    "Fig": "Higo", "Fish": "Pez", "Flesh": "Carne",
    "Flock": "Rebaño", "Fool": "Necio", "Foot": "Pie",
    "Forest": "Bosque", "Fountain": "Fuente", "Fox": "Zorro",
    "Fruit": "Fruto", "Giant": "Gigante", "Gift": "Don",
    "Glass": "Vidrio", "Goat": "Cabra", "Grape": "Uva",
    "Grass": "Hierba", "Hair": "Cabello", "Hand": "Mano",
    "Head": "Cabeza", "Herb": "Hierba", "Hill": "Colina",
    "Honey": "Miel", "Horn": "Cuerno", "Horse": "Caballo",
    "Hour": "Hora", "House": "Casa", "Hunger": "Hambre",
    "Inn": "Posada", "Island": "Isla", "Ivory": "Marfil",
    "Jewel": "Joya", "Key": "Llave", "Knife": "Cuchillo",
    "Lace": "Cordón", "Lead": "Plomo", "Leaf": "Hoja",
    "Leopard": "Leopardo", "Letter": "Carta", "Linen": "Lino",
    "Lizard": "Lagarto", "Locust": "Langosta", "Lute": "Laúd",
    "Manger": "Pesebre", "Market": "Mercado", "Meat": "Carne",
    "Milk": "Leche", "Mill": "Molino", "Mirror": "Espejo",
    "Money": "Dinero", "Moon": "Luna", "Morning": "Mañana",
    "Moth": "Polilla", "Mother": "Madre", "Mouth": "Boca",
    "Mule": "Mula", "Nail": "Clavo", "Needle": "Aguja",
    "Nest": "Nido", "Net": "Red", "North": "Norte",
    "Nose": "Nariz", "Nut": "Nuez", "Oak": "Roble",
    "Oil": "Aceite", "Onion": "Cebolla", "Oven": "Horno",
    "Owl": "Búho", "Ox": "Buey", "Palace": "Palacio",
    "Palm": "Palmera", "Pearl": "Perla", "Pen": "Pluma",
    "Pit": "Fosa", "Plain": "Llanura", "Plow": "Arado",
    "Pool": "Estanque", "Pot": "Olla", "Pottery": "Alfarería",
    "Prince": "Príncipe", "Queen": "Reina", "Quiver": "Aljaba",
    "Reed": "Caña", "Ring": "Anillo", "River": "Río",
    "Road": "Camino", "Robe": "Manto", "Rock": "Roca",
    "Rod": "Vara", "Roof": "Techo", "Root": "Raíz",
    "Rope": "Cuerda", "Rose": "Rosa", "Ruby": "Rubí",
    "Rust": "Herrumbre", "Salt": "Sal", "Sand": "Arena",
    "Seal": "Sello", "Servant": "Siervo", "Shadow": "Sombra",
    "Sheep": "Oveja", "Ship": "Nave", "Shoe": "Sandalia",
    "Shoulder": "Hombro", "Sickle": "Hoz", "Silver": "Plata",
    "Skin": "Piel", "Slave": "Esclavo", "Smoke": "Humo",
    "Snow": "Nieve", "Soldier": "Soldado", "Song": "Cántico",
    "South": "Sur", "Spear": "Lanza", "Spice": "Especia",
    "Spring": "Fuente", "Staff": "Cayado", "Sun": "Sol",
    "Table": "Mesa", "Talent": "Talento", "Tares": "Cizaña",
    "Tent": "Tienda", "Thief": "Ladrón", "Thorn": "Espina",
    "Thunder": "Trueno", "Tin": "Estaño", "Trumpet": "Trompeta",
    "Turtle": "Tórtola", "Valley": "Valle", "Veil": "Velo",
    "Vine": "Vid", "Viper": "Víbora", "Vow": "Voto",
    "Wall": "Muro", "Wasp": "Avispa", "Wave": "Ola",
    "Wax": "Cera", "Weapon": "Arma", "Well": "Pozo",
    "Whale": "Ballena", "Wheat": "Trigo", "Wheel": "Rueda",
    "Whip": "Látigo", "Wicked": "Malvado", "Wolf": "Lobo",
    "Wood": "Madera", "Wool": "Lana", "Worm": "Gusano",
    "Yoke": "Yugo",
    "Abomination": "Abominación", "Ablution": "Ablución",
    "Adjuration": "Adjuración", "Adoption": "Adopción",
    "Adultery": "Adulterio", "Advocate": "Abogado",
    "Affinity": "Afinidad", "Agriculture": "Agricultura",
    "Allegory": "Alegoría", "Alliance": "Alianza",
    "Alms": "Limosna", "Anointing": "Unción",
    "Antichrist": "Anticristo", "Apocrypha": "Apócrifos",
    "Apostasy": "Apostasía", "Architecture": "Arquitectura",
    "Archery": "Tiro con Arco",
    "Assurance": "Seguridad", "Astronomy": "Astronomía",
    "Banishment": "Destierro", "Blasphemy": "Blasfemia",
    "Blindness": "Ceguera", "Bondage": "Servidumbre",
    "Candlestick": "Candelabro", "Census": "Censo",
    "Concubine": "Concubina", "Confession": "Confesión",
    "Congregation": "Congregación", "Consecration": "Consagración",
    "Conversion": "Conversión", "Crucifixion": "Crucifixión",
    "Divination": "Adivinación", "Divorce": "Divorcio",
    "Doxology": "Doxología", "Election": "Elección",
    "Embalming": "Embalsamamiento", "Enchantments": "Encantamientos",
    "Excommunication": "Excomunión", "Exile": "Exilio",
    "Expiation": "Expiación", "Fasting": "Ayuno",
    "Fellowship": "Comunión", "Firstborn": "Primogénito",
    "Genealogy": "Genealogía", "Gentiles": "Gentiles",
    "Glorification": "Glorificación", "Hospitality": "Hospitalidad",
    "Humility": "Humildad", "Hymn": "Himno",
    "Intercession": "Intercesión", "Interpretation": "Interpretación",
    "Justification": "Justificación", "Kinsman": "Pariente",
    "Lamentation": "Lamentación", "Liberation": "Liberación",
    "Liturgy": "Liturgia", "Manifestation": "Manifestación",
    "Meditation": "Meditación", "Minstrel": "Juglar",
    "Oblation": "Oblación", "Ordination": "Ordenación",
    "Patriarch": "Patriarca", "Perfection": "Perfección",
    "Pilgrimage": "Peregrinación", "Proclamation": "Proclamación",
    "Propitiation": "Propiciación", "Providence": "Providencia",
    "Reconciliation": "Reconciliación", "Regeneration": "Regeneración",
    "Remnant": "Remanente", "Restoration": "Restauración",
    "Retribution": "Retribución", "Revelation": "Revelación",
    "Sanctification": "Santificación", "Scribe": "Escriba",
    "Sorcery": "Hechicería", "Supplication": "Súplica",
    "Transfiguration": "Transfiguración", "Tribulation": "Tribulación",
    "Uncleanness": "Impureza", "Usury": "Usura",
    "Vengeance": "Venganza",
}

# ── Multi-word pattern translations ──
PHRASE_PT = {
    "Book of": "Livro de", "Epistle to the": "Epístola aos",
    "Epistle to": "Epístola a", "Epistle of": "Epístola de",
    "Gospel of": "Evangelho de", "Mount ": "Monte ",
    "Land of": "Terra de", "Song of": "Cântico de",
    "Valley of": "Vale de", "Sea of": "Mar de",
    "Lake of": "Lago de", "Tower of": "Torre de",
    "Gate of": "Porta de", "City of": "Cidade de",
    "Plains of": "Planícies de", "Waters of": "Águas de",
    "Stone of": "Pedra de", "Sons of": "Filhos de",
    "Children of": "Filhos de", "Son of": "Filho de",
    "Course of": "Turno de", "Kingdom of": "Reino de",
    "River of": "Rio de", "Pool of": "Tanque de",
    "Well of": "Poço de", "Hill of": "Colina de",
    "House of": "Casa de", "Field of": "Campo de",
}

PHRASE_ES = {
    "Book of": "Libro de", "Epistle to the": "Epístola a los",
    "Epistle to": "Epístola a", "Epistle of": "Epístola de",
    "Gospel of": "Evangelio de", "Mount ": "Monte ",
    "Land of": "Tierra de", "Song of": "Cántico de",
    "Valley of": "Valle de", "Sea of": "Mar de",
    "Lake of": "Lago de", "Tower of": "Torre de",
    "Gate of": "Puerta de", "City of": "Ciudad de",
    "Plains of": "Llanuras de", "Waters of": "Aguas de",
    "Stone of": "Piedra de", "Sons of": "Hijos de",
    "Children of": "Hijos de", "Son of": "Hijo de",
    "Course of": "Turno de", "Kingdom of": "Reino de",
    "River of": "Río de", "Pool of": "Estanque de",
    "Well of": "Pozo de", "Hill of": "Colina de",
    "House of": "Casa de", "Field of": "Campo de",
}


def translate_name(name, known, phrases):
    # 1. Exact match
    if name in known:
        return known[name]

    # 2. Multi-word: try phrase patterns (longest first)
    for en_phrase, loc_phrase in sorted(phrases.items(), key=lambda x: -len(x[0])):
        if en_phrase.lower() in name.lower():
            pat = re.compile(re.escape(en_phrase), re.IGNORECASE)
            remainder = pat.sub("", name).strip(" ,")
            if remainder in known:
                remainder = known[remainder]
            result = f"{loc_phrase} {remainder}".strip() if remainder else loc_phrase
            return result

    # 3. "X, the" pattern
    name_clean = re.sub(r",?\s*the$", "", name, flags=re.IGNORECASE).strip()
    if name_clean != name and name_clean in known:
        return known[name_clean]

    # 4. "X or Y" / "X, Or Y" pattern
    if re.search(r",?\s+[Oo]r\s+", name):
        parts = re.split(r",?\s+[Oo]r\s+", name)
        translated = [known.get(p.strip(), p.strip()) for p in parts]
        return " ou " .join(translated) if "pt" in str(phrases) else " o ".join(translated)

    # 5. First word match for compounds
    words = name.split()
    if len(words) > 1 and words[0] in known:
        rest = " ".join(words[1:])
        return f"{known[words[0]]} {rest}"

    # 6. Keep as-is
    return name


# Apply
count = 0
changed = 0
for slug, name in unmatched:
    pt_name = translate_name(name, KNOWN_PT, PHRASE_PT)
    es_name = translate_name(name, KNOWN_ES, PHRASE_ES)

    if pt_name != name or es_name != name:
        changed += 1

    for lang, loc_name in [("pt", pt_name), ("es", es_name)]:
        db.execute(
            """UPDATE dictionary_entries_multilang
               SET name = ? WHERE slug = ? AND lang = ?""",
            [loc_name, slug, lang],
        )
    count += 1

print(f"Processed: {count}")
print(f"Actually translated (different from EN): {changed}")
print(f"Kept as EN: {count - changed}")

# Final stats
for lang in ["pt", "es"]:
    null_ct = db.execute(
        "SELECT COUNT(*) FROM dictionary_entries_multilang WHERE lang=? AND name IS NULL",
        [lang],
    ).fetchone()[0]
    total = db.execute(
        "SELECT COUNT(*) FROM dictionary_entries_multilang WHERE lang=?", [lang]
    ).fetchone()[0]
    print(f"{lang.upper()}: {total - null_ct}/{total} have name ({null_ct} null)")

# Sample
print("\nSample translations:")
for s in [
    "babylon", "moses", "exodus-book-of", "passover", "jerusalem",
    "tabernacle", "abraham", "resurrection", "adultery", "aaronites",
    "angel", "baptism", "crucifixion",
]:
    en = db.execute("SELECT name FROM dictionary_entries WHERE slug=?", [s]).fetchone()
    if not en:
        continue
    rows = db.execute(
        "SELECT lang, name FROM dictionary_entries_multilang WHERE slug=? ORDER BY lang",
        [s],
    ).fetchall()
    print(f"  {s}: EN={en[0]}")
    for lang, n in rows:
        print(f"    {lang}: {n}")

db.close()
