// Auto-generated by scripts/sentiment_status.py — do not edit manually
export const SENTIMENT_COVERED_PT: ReadonlySet<string> = new Set([
  "ECC",
  "EXO",
  "GEN",
  "JHN",
  "JOB",
  "LAM",
  "LUK",
  "PRO",
  "PSA",
  "SNG",
]);
